Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -21,10 +21,21 @@ stages:
       vmImage: ubuntu-latest
     steps:
     - task: Bash@3
+      displayName: "Linting Dockerfile"
       inputs:
         targetType: 'inline'
         script: |
           docker run --rm -i hadolint/hadolint < '$(Build.SourcesDirectory)/springboot-backend/Dockerfile'
+          
+          # check if the Hadolint command found issues or not
+          if [ $? != 0 ];
+          then
+            echo "##vso[task.logissue type=error]Lint scanning found errors in the Dockerfile that need to be resolved!"
+            echo "##vso[task.complete result=Failed]Docker Lint reporting errors"
+          else
+            echo "##vso[task.complete result=Succeeded]Docker Lint succeeded"
+          fi
+
           echo "Scan completed"
     - task: Docker@2
       displayName: Build an image
